server:
  port: 8989
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.caihua.bean
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.214:3306/exceltest?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: hua1996cai
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
